# 3. Data science
some numpy stuff

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
c = np.ones([2,2])

In [11]:
print(c)

[[1. 1.]
 [1. 1.]]


In [12]:
print(b-0.2*c)

[[0.8 1.8]
 [2.8 3.8]]


# Conditional Array Search, Filtering, Broadcasting

In [14]:
X = np.array(
 [[ 42, 40, 41, 43, 44, 43 ], # Hong Kong
 [ 30, 31, 29, 29, 29, 30 ], # New York
 [ 8, 13, 31, 11, 11, 9 ], # Berlin
 [ 11, 11, 12, 13, 11, 12 ]]) # Montreal
cities = np.array(["Hong Kong", "New York", "Berlin", "Montreal"])

    

In [17]:
np.nonzero(X >np.average(X))[0]

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2])

In [18]:
cities[np.nonzero(X >np.average(X))[0]]

array(['Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong',
       'Hong Kong', 'New York', 'New York', 'New York', 'New York',
       'New York', 'New York', 'Berlin'], dtype='<U9')

In [20]:
np.unique(cities[np.nonzero(X >np.average(X))[0]])

array(['Berlin', 'Hong Kong', 'New York'], dtype='<U9')

In [21]:
# or
set(cities[np.nonzero(X >np.average(X))[0]])

{'Berlin', 'Hong Kong', 'New York'}

In [24]:
## Data: popular Instagram accounts (millions followers)
inst = np.array([[232, "@instagram"],
 [133, "@selenagomez"],
 [59, "@victoriassecret"],
 [120, "@cristiano"],
 [111, "@beyonce"],
 [76, "@nike"]])

In [25]:
print(inst)

[['232' '@instagram']
 ['133' '@selenagomez']
 ['59' '@victoriassecret']
 ['120' '@cristiano']
 ['111' '@beyonce']
 ['76' '@nike']]


In [30]:
[x[1] for x in inst if x[0].astype(float)> 100]

['@instagram', '@selenagomez', '@cristiano', '@beyonce']

In [33]:
# np stlye
superstars = inst[inst[:,0].astype(float)>100,1]

In [34]:
print(superstars)

['@instagram' '@selenagomez' '@cristiano' '@beyonce']
